routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('home', 'App\Http\Controllers\HomeController@index')->name('home');
Route::group(['prefix' => 'admin'], function () {
    Route::resource('users', 'App\Http\Controllers\Admin\UsersController');
    Route::resource('roles', 'App\Http\Controllers\Admin\RolesController');
    Route::get('permissions', 'App\Http\Controllers\Admin\PageController@permission_index');
    Route::get('countries', 'App\Http\Controllers\Admin\PageController@country_index');
    Route::get('states', 'App\Http\Controllers\Admin\PageController@state_index');
    Route::get('cities', 'App\Http\Controllers\Admin\PageController@city_index');
    Route::get('departments', 'App\Http\Controllers\Admin\PageController@department_index');
    Route::get('employees', 'App\Http\Controllers\Admin\PageController@employee_index');
    

});

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Permission;
use App\Models\User;
class Role extends Model
{
    use HasFactory;

    protected $fillable = [
        'name', 'display_name', 'description'
    ];
    /**

     * The attributes that should be mutated to dates.

     *

     * @var array

     */

    protected $dates = ['deleted_at'];


    public function permissions() {

        return $this->belongsToMany(Permission::class);
           
     }
     
     public function users() {
     
        return $this->belongsToMany(User::class);
            
     }
}

app/Http/Controllers/Admin/RolesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use DB;
class RolesController extends Controller
{

    function __construct()
    {
        // $this->middleware('permission:role-list|role-create|role-edit|role-delete', ['only' => ['index','store']]);
        // $this->middleware('permission:role-create', ['only' => ['create','store']]);
        // $this->middleware('permission:role-edit', ['only' => ['edit','update']]);
        // $this->middleware('permission:role-delete', ['only' => ['destroy']]);
    }
    /**
    * Display a listing of the resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function index(Request $request)
    {
    $roles = Role::orderBy('id','DESC')->paginate(5);
        return view('roles.index',compact('roles'))
        ->with('i', ($request->input('page', 1) - 1) * 5);
    }
    /**
    * Show the form for creating a new resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function create()
    {
        $permission = Permission::get();
        return view('roles.create',compact('permission'));
    }
    /**
    * Store a newly created resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @return \Illuminate\Http\Response
    */
    public function store(Request $request)
    {
        $this->validate($request, [
        'name' => 'required|unique:roles,name',
        'permission' => 'required',
        ]);
        $role = Role::create(['name' => $request->input('name')]);
        $role->syncPermissions($request->input('permission'));
        return redirect()->route('roles.index')
        ->with('success','Role created successfully');
    }
    /**
    * Display the specified resource.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function show($id)
    {
        $role = Role::find($id);
        $rolePermissions = Permission::join("role_has_permissions","role_has_permissions.permission_id","=","permissions.id")
        ->where("role_has_permissions.role_id",$id)
        ->get();
        return view('roles.show',compact('role','rolePermissions'));
    }
    /**
    * Show the form for editing the specified resource.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function edit($id)
    {
        $role = Role::find($id);
        $permission = Permission::get();
        $rolePermissions = DB::table("role_has_permissions")->where("role_has_permissions.role_id",$id)
        ->pluck('role_has_permissions.permission_id','role_has_permissions.permission_id')
        ->all();
        return view('roles.edit',compact('role','permission','rolePermissions'));
    }
    /**
    * Update the specified resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
        'name' => 'required',
        'permission' => 'required',
        ]);
        $role = Role::find($id);
        $role->name = $request->input('name');
        $role->save();
        $role->syncPermissions($request->input('permission'));
        return redirect()->route('roles.index')
        ->with('success','Role updated successfully');
    }
    /**
    * Remove the specified resource from storage.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function destroy($id)
    {
        DB::table("roles")->where('id',$id)->delete();
        return redirect()->route('roles.index')
        ->with('success','Role deleted successfully');
    }
}

app/Http/Controllers/Api/v1/RolesController.php
<?php

namespace App\Http\Controllers\Api\v1;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Role;
use App\Models\Permission;
use DB;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Auth;

class RolesController extends ApiController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return response()->json(Role::get());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        // 
        $role = new Role();
        $role->name = $request->input('name');
        $role->display_name = $request->input('display_name');
        $role->description = $request->input('description');
        $role->save();
        
        
        return 201;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $role = Role::find($id);
        $rolePermissions = Permission::join("permission_role","permission_role.permission_id","=","permissions.id")
            ->where("permission_role.role_id",$id)
            ->get();
        
        return response()->json($role);
    }
    public function showRolePermissions($id)
    {
        $rolePermissions = Permission::join("permission_role","permission_role.permission_id","=","permissions.id")
            ->where("permission_role.role_id",$id)
            ->get();
        
        return response()->json($rolePermissions);
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $role = Role::find($id);
        $role->display_name = $request->input('display_name');
        $role->description = $request->input('description');
        $role->save();

        DB::table("permission_role")->where("permission_role.role_id",$id)
            ->delete();

        foreach ($request->input('permission') as $key => $value) {
            $role->attachPermission($value);
        }

        return 202;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::table("roles")->where('id',$id)->delete();

        return 200;
    }
}

resources/views/roles/create.blade.php
@extends('layouts.auth')
@section('content')



<div>
    <div class="page-header">
      <h3 class="page-title">Dashboard</h3>
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href>Dashboard</a>
          </li>
          <li class="breadcrumb-item" aria-current="page">
            <a class="float-right" href="{{ route('roles.index') }}">Roles</a>
          </li>
          <li class="breadcrumb-item active" aria-current="page">Create New User</li>
        </ol>
      </nav>
    </div>

    <div class="card">
      <div class="card-header">
      Create New User
        <div class="card-header-actions">
        <a class="float-right" href="{{ route('roles.index') }}">Back</a>
        </div>
        <!--card-header-actions-->
      </div>
      <!--card-header-->

      <div class="card-body">
      {!! Form::open(array('route' => 'roles.store','method'=>'POST')) !!}
          
        <div class="form-group row">
            <label for="name" class="col-md-2 col-form-label">Name</label>
            <div class="col-md-10">
            {!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control')) !!}
            </div>
         </div>
         @foreach($permission as $value)
            <label>{{ Form::checkbox('permission[]', $value->id, false, array('class' => 'name')) }}
            {{ $value->name }}</label>
            <br/>
          @endforeach

          <button class="btn btn-sm btn-primary float-right" type="submit">Create Role</button>
          {!! Form::close() !!}
      </div>
    </div>
  </div>

  @endsection

resources/views/roles/edit.blade.php
@extends('layouts.auth')
@section('content')



<div>
    <div class="page-header">
      <h3 class="page-title">Dashboard</h3>
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href>Dashboard</a>
          </li>
          <li class="breadcrumb-item" aria-current="page">
            <a class="float-right" href="{{ route('roles.index') }}">Roles</a>
          </li>
          <li class="breadcrumb-item active" aria-current="page">Edit New Role</li>
        </ol>
      </nav>
    </div>

    <div class="card">
      <div class="card-header">
      Edit New User
        <div class="card-header-actions">
          <a class="float-right" href="{{ route('roles.index') }}">Back</a>
        </div>
        <!--card-header-actions-->
      </div>
      <!--card-header-->

      <div class="card-body">
      {!! Form::model($role, ['method' => 'PATCH','route' => ['roles.update', $role->id]]) !!}
        <div class="form-group row">
            <label for="name" class="col-md-2 col-form-label">Username</label>
            <div class="col-md-10">
            {!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control')) !!}
            </div>
         </div>
          
         @foreach($permission as $value)
          <label>{{ Form::checkbox('permission[]', $value->id, in_array($value->id, $rolePermissions) ? true : false, array('class' => 'name')) }}
          {{ $value->name }}</label>
          <br/>
          @endforeach
          

          <button class="btn btn-sm btn-primary float-right" type="submit">Update Role</button>
          {!! Form::close() !!}
      </div>
    </div>
  </div>

  @endsection

resources/views/roles/index.blade.php
@extends('layouts.auth')

@section('content')
<div>
    <div class="page-header">
      <h3 class="page-title">Dashboard</h3>
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{{ url('/home') }}">Dashboard</a>
          </li>
          <li class="breadcrumb-item" aria-current="page">
            <a href="{{ route('roles.index') }}">Role</a>
          </li>
        </ol>
      </nav>
    </div>

    <div class="card">
      <div class="card-header">
        <i class="fa fa-align-justify"></i> Roles Listing
        <a class="float-right" href="{{ route('roles.create') }}"> + Create New Role</a>
      </div>
      <div class="card-body">
      <table class="table table-responsive-sm mt-3">
        <tr>
          <th>No</th>
          <th>Name</th>
          <th width="280px">Action</th>
        </tr>
          @foreach ($roles as $key => $role)
        <tr>
          <td>{{ ++$i }}</td>
          <td>{{ $role->name }}</td>
          <td>
          <a class="btn btn-info" href="{{ route('roles.show',$role->id) }}">Show</a>
          @can('role-edit')
          <a class="btn btn-primary" href="{{ route('roles.edit',$role->id) }}">Edit</a>
          @endcan
          @can('role-delete')
          {!! Form::open(['method' => 'DELETE','route' => ['roles.destroy', $role->id],'style'=>'display:inline']) !!}
          {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
          {!! Form::close() !!}
          @endcan
          </td>
        </tr>
        @endforeach
        </table>
      </div>
    </div>
  </div>

@endsection

resources/views/roles/show.blade.php
@extends('layouts.auth')
@section('content')



<div>
    <div class="page-header">
      <h3 class="page-title">Dashboard</h3>
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href>Dashboard</a>
          </li>
          <li class="breadcrumb-item" aria-current="page">
            <a class="float-right" href="{{ route('users.index') }}">User</a>
          </li>
          <li class="breadcrumb-item active" aria-current="page">Edit New User</li>
        </ol>
      </nav>
    </div>

    <div class="card">
      <div class="card-header">
      User Info
        <div class="card-header-actions">
          <a class="float-right" href="{{ route('users.index') }}">Back</a>
        </div>
        <!--card-header-actions-->
      </div>
      <!--card-header-->

      <div class="card-body">


        <div class="form-group row">
            <label for="name" class="col-md-2 col-form-label">Roles</label>
            <div class="col-md-10">
            @if(!empty($rolePermissions))
            @foreach($rolePermissions as $v)
            <label class="label label-success">{{ $v->name }},</label>
            @endforeach
            @endif
            </div>
        </div>
        
      </div>
    </div>
  </div>

  @endsection